package com.devops.products.mapper;

import com.devops.products.model.Memo;
import com.devops.products.model.MemoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int countByExample(MemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int deleteByExample(MemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `memo`",
        "where `memo_id` = #{memoId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer memoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `memo` (`memo_id`, `user_id`, ",
        "`product_name`, `start_time`, ",
        "`exp`)",
        "values (#{memoId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{productName,jdbcType=VARCHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{exp,jdbcType=INTEGER})"
    })
    int insert(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int insertSelective(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    List<Memo> selectByExample(MemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`memo_id`, `user_id`, `product_name`, `start_time`, `exp`",
        "from `memo`",
        "where `memo_id` = #{memoId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Memo selectByPrimaryKey(Integer memoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Memo record, @Param("example") MemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Memo record, @Param("example") MemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    @Update({
        "update `memo`",
        "set `user_id` = #{userId,jdbcType=INTEGER},",
          "`product_name` = #{productName,jdbcType=VARCHAR},",
          "`start_time` = #{startTime,jdbcType=TIMESTAMP},",
          "`exp` = #{exp,jdbcType=INTEGER}",
        "where `memo_id` = #{memoId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Memo record);
}