package com.devops.products.model;

import java.util.Date;

public class Memo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memo_id
     *
     * @mbggenerated
     */
    private Integer memoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.exp
     *
     * @mbggenerated
     */
    private Integer exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memo_id
     *
     * @return the value of memo.memo_id
     *
     * @mbggenerated
     */
    public Integer getMemoId() {
        return memoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memo_id
     *
     * @param memoId the value for memo.memo_id
     *
     * @mbggenerated
     */
    public void setMemoId(Integer memoId) {
        this.memoId = memoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.user_id
     *
     * @return the value of memo.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.user_id
     *
     * @param userId the value for memo.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.product_name
     *
     * @return the value of memo.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.product_name
     *
     * @param productName the value for memo.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.start_time
     *
     * @return the value of memo.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.start_time
     *
     * @param startTime the value for memo.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.exp
     *
     * @return the value of memo.exp
     *
     * @mbggenerated
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.exp
     *
     * @param exp the value for memo.exp
     *
     * @mbggenerated
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }
}